# Generated by Django 4.2.13 on 2024-06-05 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_fio', models.CharField(max_length=100)),
                ('user_photo', models.ImageField(upload_to='')),
            ],
        ),
    ]
